### ISSUE TITLE
link search page controller to model_interface.php

### ISSUE THREAD

**Issue by carlosmartinezvillar** [joemelt101/gamer-net#108]

**Comment by joemelt101** [comment]
Search by games played
Search by Alias
Search by ZipCode (Closest to furthest from entered zip)

**Comment by HomerGaidarski** [comment]
User search works for searching by alias or username; doesn't matter. Game search works for name or developer. Location search works for city, state, zip code;

NOTE: For location and game, no html tags are surrounding pieces of data (i'm just echoing it as plain text), that's up to you Carlos. For location, duplicate locations can appear since locations are linked to users and 2 users can have the same location, need to add logic to handle this and maybe display a list of users who are at the same location (city, state, zip all the same). Also locations are not ordered by closest zip code yet, need to use an api for this.
